/**
 * Created by MosinVE on 06.04.2017.
 */
const ADD_OBJECT = 'ADD_OBJECT'
const EDIT_OBJECT = 'EDIT_OBJECT'
const ADD_PROP = 'ADD_PROP'
const EDIT_PROP = 'EDIT_PROP'
const GET_PROPERTIES = 'GET_PROPERTIES'
export const objects = {ADD_ITEM: ADD_OBJECT, EDIT_ITEM: EDIT_OBJECT}
export const properties = {ADD_ITEM: ADD_PROP, EDIT_ITEM: EDIT_PROP, GET_ITEMS: GET_PROPERTIES}
